### PR TITLE
Performance tweaks

### PR DESCRIPTION
**Pull request by pboehm**
This PR adds some performance improvements by implementing `prefetching` of related objects (enabled by default) and assigning related objects by their id.

Increases version to 0.2.0.

### CODE REVIEW

**Comment by aidanlister** [comment]
Amazing! I've got this running now. One thing worth mentioning is that if you're using operators, you need to disable prefetch, otherwise you'll get something like:

```
AttributeError: 'Contractor' object has no attribute 'name__iexact'
```

My is_a looks like:

```
  column_description = {
      'property': is_a(Property, search_attr="ref", fk=True),
      'contractor': is_a(Contractor, search_attr="name__iexact", fk=True),
      'report_type_key': is_a(exclude=True),
      'type_suggestion': is_a(exclude=True),
  }
```

Using database operators wasn't documented anywhere, so I'm not sure if it's worth adding this to the docs.

**Comment by aidanlister** [comment]
My migration is only about half way through, so I'm not sure there's been a significant speed improvement -- I'm doing a lot of database work in post_save / pre_save which is probably what's keeping it slow, I will spend some time optimizing that and see the speed improvements materialize. 

Can you think of a neat way of optimizing lookups based on multiple properties? E.g. I call this just under half a million times:

```
        instance.report = Report.objects.get(property=instance.property, type=instance.type)
```

Maybe a 2D defaultdict?

**Comment by aidanlister** [comment]
This is what I've gone with:

```
@classmethod
def hook_before_all(self):
    schedulemap = defaultdict(lambda : defaultdict(dict))
    schedules = ReportSchedule.objects.all()
    for schedule in schedules:
        schedulemap[schedule.property_id][schedule.type_id] = schedule
    self.schedulemap = schedulemap

@classmethod
def hook_after_save(self, instance, row):
    schedule = self.schedulemap[instance.property_id][row['type_id']]
    if schedule:
        instance.report_schedule.add(rs)
```

I'm sure this could be abstracted further into a migrations.CachedLookup class or something, but for now I think it's sufficient to be in user space. My migrations are running now, will report the speed improvement soon!

**Comment by pboehm** [comment]
I would rather use a simple dict with multiple properties as key (joined in a tuple). This reduces the number of hash lookups. Using a `dict` instead of a `defaultdict` is more performant in case of a lookup which does not exist, where the defaultdict will create a new entry each time using another function call.

``` python
@classmethod
def hook_before_all(self):
    self.schedulemap = dict(
        ((sched.property_id, sched.type_id), sched)
            for sched in ReportSchedule.objects.all()
    )

@classmethod
def hook_after_save(self, instance, row):
    schedule = self.schedulemap.get( (instance.property_id, row['type_id'],), None)
    if schedule:
        instance.report_schedule.add(rs)
```

Regarding your first comment: I haven't thought about using database operators in the search_attr because my search_attr fields are all case sensitive. When I add a section about "prefetching ...." to the docs I will add a note concerning database operators.

**Comment by aidanlister** [comment]
Woooo! 41m43.293s

That's at least a 3x improvement in speed! Thanks for the tip about using a tuple as key, I didn't think to do that, very nifty.

**Comment by pboehm** [comment]
That's really cool ...

**Pull request merged**
